# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x05visao\x1a\x1bgoogle/protobuf/empty.proto\"\x13\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\t2<\n\x05VisAO\x12\x33\n\tGetImages\x12\x16.google.protobuf.Empty\x1a\x0c.visao.Image\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGE']._serialized_start=50
  _globals['_IMAGE']._serialized_end=69
  _globals['_VISAO']._serialized_start=71
  _globals['_VISAO']._serialized_end=131
# @@protoc_insertion_point(module_scope)
