name: Frontend - lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x.x
          cache: npm
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint