name: Protobuf generated files check

on:
  push:
    

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x.x
          cache: npm
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build protobuf
        run: npm run proto:build
      
      - name: Check if frontend generated files differ
        run: git diff --quiet src/gen/**
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup poetry
        uses: snok/install-poetry@v1
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        
      - name: Install dependencies
        run: poetry install
      
      - name: Build protobuf
        run: poetry run ./generate_proto.sh

      - name: Check if backend generated files differ
        run: git diff --quiet visao_backend/visao_grpc/**